### ISSUE TITLE
Not currently a netbox-plugin

### ISSUE THREAD

**Issue by ryanmerolle** [netdotwork/netbox_resolver#1]
This is a script does not strictly adhere to the definition of a NetBox plugin, yet the topic is applied.  Its not a huge deal, just confusing for users since it has been tagged as such.  Its also not a NetBox script (IE a python script that leverages the NetBox ui & extensibility functions provides by NetBox custom scripts function).

**Comment by netdotwork** [comment]
deleted netbox-plugin topic
